create table if not exists public.spot_submission_attempts (
    id bigint generated by default as identity primary key,
    visitor_hash text not null,
    created_at timestamptz not null default now()
);

create index if not exists spot_submission_attempts_visitor_created_idx
    on public.spot_submission_attempts (visitor_hash, created_at desc);

alter table public.spot_submission_attempts enable row level security;

revoke all on table public.spot_submission_attempts from anon, authenticated;

-- Neue Spots dürfen nur noch über die Edge Function angelegt werden.
-- UPDATE bleibt vorerst bestehen, weil die vorhandene Meldefunktion es verwendet.
revoke insert on table public.spots from anon, authenticated;

-- Alte Rate-Limit-Daten sollten regelmäßig gelöscht werden, zum Beispiel täglich:
-- delete from public.spot_submission_attempts where created_at < now() - interval '24 hours';
